### ISSUE TITLE
networkextention misspelled

### ISSUE THREAD

**Issue by codefromthecrypt** [mosn/mosn#2159]
networkextention is misspelled. It would break people to fix it, but I think it is worth fixing.

**Comment by doujiang24** [comment]
@codefromthecrypt Nice catch!
Do you mean `networkextention` in https://github.com/mosn/mosn/tree/master/pkg/networkextention?

It will be replaced by a new implementation, based on https://github.com/mosn/envoy-go-extension
We prefer not to fix it since it will be replaced soon.

Closing it, feel free to open it when you have other questions.
